### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by adambkaplan** [manifestival/controller-runtime-client#3]
I am one of the maintainers of https://github.com/shipwright-io/operator, which includes manifestival/controller-runtime-client as a direct dependency. We have noticed that this project has not kept up to date with manifestival/manifestival with respect to dependency updates, nor has it had a release in quite some time.

Do the maintainers intend to keep this project alive? Are you willing to consider opening this up for "adoption" or bring on new maintainers?

**Comment by jcrossley3** [comment]
It's not my primary focus these days, but I'm happy to merge PR's and cut releases when needed. Open to bringing on new maintainers as well.

**Comment by adambkaplan** [comment]
I can work with "PRs welcome!" :smile_cat:. I'd be happy to send over a dependency update.

**Comment by jcrossley3** [comment]
Assuming this is closed by #4
